NAMESPACE ?= $(shell basename `pwd`)
PACKAGES ?= $(shell find $(HELM_VALUES_PATH)/$(NAMESPACE) -type f -name '*.yaml' | xargs -n 1 -I '{}' basename {} .yaml)

## Very basic validation that configuration directory exists for this namespace
validate:
	@if [ ! -d  $(HELM_VALUES_PATH)/$(NAMESPACE) ]; then \
		echo "No values for $(NAMESPACE) found in $(HELM_VALUES_PATH)/$(NAMESPACE)"; \
		exit 1; \
	fi

## List configured packages for this namespace
list-available: validate
	@echo "Packages configured in the $(NAMESPACE) namespace:"
	@echo $(PACKAGES) | xargs -n 1 printf -- ' - %s\n'

## List installed packages for this namespace
list-installed: validate
	@echo "Packages configured and installed in $(NAMESPACE)"
	@helm list `echo $(PACKAGES) | xargs -n 1 printf -- '%s\n' | paste -s -d\| - | xargs printf '^(%s)$$'`

## List configurations for this namespace
list-configs: validate
	@echo "Configurations for $(NAMESPACE)"
	@find $(HELM_VALUES_PATH)/$(NAMESPACE) -type f -name '*.yaml' | xargs -n 1 printf ' - %s\n'

## Install packages for this namespace
install: module

## Uninstall packages for this namespace
uninstall: module

## Configure packages for this namespace
config: module

