#!/bin/bash
DOCKER_IMAGE=${DOCKER_IMAGE:-cloudposse/geodesic}
DOCKER_TAG=${DOCKER_TAG:-dev}
STATE_DIR=${STATE_DIR:-${HOME}/.geodesic}
mkdir -p ${STATE_DIR}
docker run \
  --env LS_COLORS \
  --env TERM \
  --env TERM_COLOR \
  --env SSH_AUTH_SOCK \
  --rm \
  -it \
  --volume ${STATE_DIR}:/geodesic/config \
    ${DOCKER_IMAGE} $*
