name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
version-resolver:
  major:
    labels:
    - 'major'
  minor:
    labels:
    - 'minor'
    - 'enhancement'
  patch:
    labels:
    - 'auto-update'
    - 'patch'
    - 'fix'
    - 'bugfix'
    - 'bug'
    - 'hotfix'
    - 'packages'
    - 'docker'
    - 'docs'
    - 'github'
  default: 'minor'

exclude-labels:
  - 'alpine-only'

categories:
- title: '🚀 Enhancements'
  labels:
  - 'enhancement'
  - 'patch'
  - 'shell'
  - 'scripts'
  - 'terraform'
- title: '🐛 Bug Fixes'
  labels:
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'hotfix'
- title: '🧰 Included Tools'
  labels:
  - 'packages'
  - 'docker'
- title: '📚️ Documentation'
  labels:
  - 'docs'
- title: '🏗️ Build/Release Maintenance'
  labels:
  - 'github'

change-template: |
  <details>
    <summary>$TITLE @$AUTHOR (#$NUMBER)</summary>

    $BODY
  </details>

template: |
  $CHANGES

  ## Every Release
  
  In every release, we update all [unpinned packages](https://github.com/cloudposse/geodesic/blob/main/packages.txt) to their latest packaged versions.
  
  On a regular basis (roughly weekly), on Alpine only, we update the AWS CLI v1 and its dependencies to the latest versions. Debian does not have AWS CLI v1 installed, only v2.
  
  These changes are not detailed here.

replacers:
# Remove irrelevant information from Renovate bot
- search: '/(?<=---\s+)^#.*(Renovate configuration|Configuration)(?:.|\n)*?This PR has been generated .*/gm'
  replace: ''
# Remove Renovate bot banner image
- search: '/\[!\[[^\]]*Renovate\][^\]]*\](\([^)]*\))?\s*\n+/gm'
  replace: ''
