language: en-US
tone_instructions: ''
early_access: true
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: false
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  poem: false
  labeling_instructions: []
  path_filters: []
  path_instructions: []
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  finishing_touches:
    docstrings:
      enabled: true
  tools:
    shellcheck:
      enabled: true
    ruff: # for Python
      enabled: false
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_only: false
      level: default
    biome: # For JavaScript/TypeScript
      enabled: false
    hadolint:
      enabled: true
    swiftlint: # For Swift
      enabled: false
    phpstan: # For PHP
      enabled: false
      level: default
    golangci-lint: # For Go
      enabled: false
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt: # For Kotlin
      enabled: false
    eslint: # For JavaScript/TypeScript
      enabled: false
    rubocop: # For Ruby
      enabled: false
    buf: # For Protobuf
      enabled: false
    regal: # For Rego
      enabled: false
    actionlint:
      enabled: true
    pmd: # For Java
      enabled: false
    cppcheck: # For C/C++
      enabled: false
    semgrep: # Static analysis. CodeRabbit recommends disabling this tool unless you configure specific rules for it.
      enabled: false
    circleci: # For CircleCI
      enabled: false
chat:
  auto_reply: true
  integrations:
    jira:
      usage: disabled
    linear:
      usage: disabled
knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: disabled
    project_keys: []
  linear:
    usage: disabled
    team_keys: []
  pull_requests:
    scope: auto
