# Build a service with environment variables
version: '1.0'

stages:
  - Build
  - Push
steps:
  build_image:
    title: Build image
    type: build
    stage: Build
    description: Build geodesic
    image_name: ${{CF_REPO_NAME}}
    dockerfile: Dockerfile

  push_image_commit:
    title: Push image with commit sha tag
    type: push
    stage: Push
    candidate: ${{build_image}}
    registry: dockerhub
    tags:
      - "${{SEMVERSION_COMMIT}}"

  push_image_branch:
    title: Push image with branch tag
    type: push
    stage: Push
    candidate: ${{build_image}}
    registry: dockerhub
    tags:
      - "${{CF_BRANCH}}"
    when:
      condition:
        all:
          executeForBranch: "'${{CF_BRANCH}}' != ''"

  push_image_tag:
    title: Push image with release tag
    type: push
    stage: Push
    candidate: ${{build_image}}
    registry: dockerhub
    tag: "${{CF_RELEASE_TAG}}"
    when:
      condition:
        all:
          executeForTag: "'${{CF_RELEASE_TAG}}' != ''"

  push_image_latest:
    title: Push image with latest tag
    type: push
    stage: Push
    candidate: ${{build_image}}
    registry: dockerhub
    tag: latest
    when:
      condition:
        all:
          executeForMasterBranch: "'${{CF_BRANCH}}' == 'master'"
