# Demo of Geodesic

Output docs/gifs/demo.gif
Output docs/mp4/demo.mp4
Output docs/webm/demo.webm

Set Theme "Catppuccin Frappe"

Set WindowBar Colorful

Set CursorBlink true

Set BorderRadius 10

Set Padding 20

Set FontSize 12
Set Width 1200
Set Height 600
Set PlaybackSpeed 1.2

Set Shell bash

Sleep 1.5s
Type "make all"
Enter

Sleep 6.5s

Type "terraform -help"
Enter

Sleep 3s

Type "aws help"
Enter

Sleep 3s

Type "q"
Sleep 500ms

Type "quit"
Enter

Type "exit"
Enter
Ctrl+D

