NAMESPACE ?= $(shell basename $(abspath $(shell pwd)/../))
PACKAGES ?= $(shell grep -E '^[a-zA-Z0-9\-\:]+:' Makefile | sed 's/:$$//g')

define chart-values
	@if [ -f "$(HELM_VALUES_PATH)/$(NAMESPACE)/$(1).yaml" ]; then \
		echo "$(1) already configured in $(HELM_VALUES_PATH)/$(NAMESPACE)/$(1).yaml"; \
	else \
		echo "Fetching config for $(1) from $(2)"; \
		mkdir -p  $(HELM_VALUES_PATH)/$(NAMESPACE); \
		helm inspect values $(2) | sed 's/^/#/' > $(HELM_VALUES_PATH)/$(NAMESPACE)/$(1).yaml; \
	fi
endef

## Configure all packages
all: $(PACKAGES)

## List current configurations
list:
	@echo "# Configs in $(HELM_VALUES_PATH)/$(NAMESPACE)"
	@find $(HELM_VALUES_PATH)/$(NAMESPACE) -type f -name '*.yaml' | xargs ls -l
