apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    server: https://{{ getenv "KOPS_API_SERVER" }}
    certificate-authority-data: {{ getenv "KOPS_CLUSTER_CA" | base64.Encode }}
  name: {{ getenv "KOPS_CLUSTER_NAME" }}

contexts:
- context:
    cluster: {{ getenv "KOPS_CLUSTER_NAME" }}
    user: {{ getenv "KOPS_CLUSTER_NAME" }}
  name: {{ getenv "KOPS_CLUSTER_NAME" }}

current-context: {{ getenv "KOPS_CLUSTER_NAME" }}

{{- if bool (getenv "KOPS_AWS_IAM_AUTHENTICATOR_ENABLED" "false") }}
users:
- name: {{ getenv "KOPS_CLUSTER_NAME" }}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - token
        - -i
        - {{ getenv "KOPS_CLUSTER_NAME" }}
{{- end }}
