include helpers
include distro/uninstall

## Uninstall DNS
dns:
	$(call chart-uninstall)

## Uninstall SSL
ssl:
	$(call chart-uninstall)

## Uninstall SSH
ssh:
	$(call chart-uninstall)

## Uninstall UI
ui:
	$(call chart-uninstall)

## Uninstall Etcd Operator
etcd-operator:
	$(call chart-uninstall)

## Uninstall log aggregation
logs:
	$(call chart-uninstall)

## Uninstall monitoring
monitoring:
	$(call chart-uninstall)

## Uninstall metrics
metrics:
	$(call chart-uninstall)

## Uninstall Data Dog
dd:
	$(call chart-uninstall)

