helmDefaults:
  args:
    - "--wait"
    - "--recreate-pods"
    - "--timeout=600" 
    - "--force"
    - "--reset-values"

repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:

################################################################################
## Chart Museum ################################################################
################################################################################

- name: "charts"
  namespace: "kube-system"
  labels:
    chart: "chartmuseum"
    component: "platform"
    namespace: "kube-system"
    vendor: "kubernetes-helm"
    default: "true"
  chart: "stable/chartmuseum"
  version: "1.4.0"
  values:
    - "values/chartmuseum.yaml"
  set:
    - name: "replicaCount"
      value: "1"

    # disable all routes prefixed with /api
    - name: "env.open.DISABLE_API"
      value: "true"

    # show debug messages
    - name: "env.open.DEBUG"
      value: '{{ env "CHARTMUSEUM_DEBUG" | default "false" }}'

    # allow chart versions to be re-uploaded
    - name: "env.open.ALLOW_OVERWRITE"
      value: "false"

    # use amazon s3 storage as backend
    - name: "env.open.STORAGE"
      value: "amazon"

    ### Required: CHARTMUSEUM_STORAGE_AMAZON_BUCKET;
    - name: "env.open.STORAGE_AMAZON_BUCKET"
      value: '{{ env "CHARTMUSEUM_STORAGE_AMAZON_BUCKET" }}'

    ### Required: CHARTMUSEUM_STORAGE_AMAZON_PREFIX; e.g. /
    - name: "env.open.STORAGE_AMAZON_PREFIX"
      value: '{{ env "CHARTMUSEUM_STORAGE_AMAZON_PREFIX" }}'

    ### Required: CHARTMUSEUM_STORAGE_AMAZON_REGION; e.g. us-west-2
    - name: "env.open.STORAGE_AMAZON_REGION"
      value: '{{ env "CHARTMUSEUM_STORAGE_AMAZON_REGION" }}'

    ### Required: CHARTMUSEUM_BASIC_AUTH_USER; e.g. server
    - name: "env.secret.BASIC_AUTH_USER"
      value: '{{ env "CHARTMUSEUM_BASIC_AUTH_USER" }}'

    ### Required: CHARTMUSEUM_BASIC_AUTH_PASS; e.g. 15041434-3DC2-42F8-9358-F8AED8780A66
    - name: "env.secret.BASIC_AUTH_PASS"
      value: '{{ env "CHARTMUSEUM_BASIC_AUTH_PASS" }}'

    ### Required: CHARTMUSEUM_IAM_ROLE;
    - name: "replica.annotations.iam\\.amazonaws\\.com/role"
      value: '{{ env "CHARTMUSEUM_IAM_ROLE" }}'

    ## Resources
    - name: "resources.limits.cpu"
      value: "100m"

    - name: "resources.limits.memory"
      value: "512Mi"

    - name: "requests.cpu"
      value: "5m"

    - name: "requests.memory"
      value: "256Mi"

    ## Ingress
    - name: "ingress.enabled"
      value: "true"

    - name: "ingress.annotations.kubernetes\\.io/ingress\\.class"
      value: "nginx"

    # FIXME: this is blocked by https://github.com/roboll/helmfile/issues/119
    #- name: "ingress.annotations.kubernetes\\.io/tls-acme"
    #  value: "true"
    
    ### Required: CHARTMUSEUM_HOSTNAME; e.g. e.g. charts.us-west-2.staging.cloudposse.org
    - name: "ingress.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
      value: '{{ env "CHARTMUSEUM_HOSTNAME" }}'

    ### Required: CHARTMUSEUM_INGRESS; e.g. ingress.us-west-2.staging.cloudposse.org
    - name: "ingress.annotations.external-dns\\.alpha\\.kubernetes\\.io/target"
      value: '{{ env "CHARTMUSEUM_INGRESS" }}'

    # DNS TTL for CHARTMUSEUM_HOSTNAME; e.g. 60
    # FIXME: this is blocked by https://github.com/roboll/helmfile/issues/119
    #- name: "ingress.annotations.external-dns\\.alpha\\.kubernetes\\.io/ttl"
    #  value: "60"

    ### Required: CHARTMUSEUM_HOSTNAME; e.g. charts.us-west-2.staging.cloudposse.org
    - name: 'ingress.hosts.{{ env "CHARTMUSEUM_HOSTNAME" | replace "." "\\." }}[0]'
      value: "/charts"

    ### Required: CHARTMUSEUM_HOSTNAME; e.g. charts.us-west-2.staging.cloudposse.org
    - name: 'ingress.hosts.{{ env "CHARTMUSEUM_HOSTNAME" | replace "." "\\." }}[1]'
      value: "/index.yaml"

    ### Optional: CHARTMUSEUM_SECRET_NAME; e.g. chartmuseum-server-tls
    - name: "ingress.tls[0].secretName"
      value: '{{ env "CHARTMUSEUM_SECRET_NAME" | default "chartmuseum-server-tls" }}'

    ### Required: CHARTMUSEUM_HOSTNAME; e.g. charts.us-west-2.staging.cloudposse.org
    - name: "ingress.tls[0].hosts[0]"
      value: '{{ env "CHARTMUSEUM_HOSTNAME" }}'
