helmDefaults:
  args:
    - "--wait"
    - "--recreate-pods"
    - "--timeout=600" 
    - "--force"
    - "--reset-values"

repositories:
# CoreOS Stable helm charts
- name: "coreos-stable"
  url: "https://s3-eu-west-1.amazonaws.com/coreos-charts/stable"

releases:

#######################################################################################
## prometheus-operator                                                               ##
## creates/configures/manages Prometheus clusters atop Kubernetes                    ##
#######################################################################################

#
# References:
#   - https://github.com/coreos/prometheus-operator/tree/master/helm/prometheus-operator
#   - https://github.com/coreos/prometheus-operator
#
- name: "prometheus-operator"
  namespace: "kube-system"
  labels:
    chart: "prometheus-operator"
    component: "monitoring"
    namespace: "kube-system"
    vendor: "coreos"
    default: "true"
  chart: "coreos-stable/prometheus-operator"
  version: "0.0.23"
  values:
    - rbacEnable: false
      jobLabel: "prometheus-operator"
      image:
        repository: "quay.io/coreos/prometheus-operator"
        ### Optional: PROMETHEUS_OPERATOR_IMAGE_TAG; e.g. v0.17.0
        tag: '{{ env "PROMETHEUS_OPERATOR_IMAGE_TAG" | default "v0.17.0" }}'
        pullPolicy: "IfNotPresent"
      resources:
        limits:
          cpu: "10m"
          memory: "64Mi"
        requests:
          cpu: "5m"
          memory: "32Mi"
      global:
        hyperkube:
          repository: "quay.io/coreos/hyperkube"
          ### Optional: PROMETHEUS_OPERATOR_GLOBAL_HYPERKUBE_IMAGE_TAG; e.g. v1.7.6_coreos.0
          tag: '{{ env "PROMETHEUS_OPERATOR_GLOBAL_HYPERKUBE_IMAGE_TAG" | default "v1.7.6_coreos.0" }}'
          pullPolicy: "IfNotPresent"
      prometheusConfigReloader:
        repository: "quay.io/coreos/prometheus-config-reloader"
        ### Optional: PROMETHEUS_OPERATOR_PROMETHEUS_CONFIG_RELOADER_IMAGE_TAG; e.g. v0.0.3
        tag: '{{ env "PROMETHEUS_OPERATOR_PROMETHEUS_CONFIG_RELOADER_IMAGE_TAG" | default "v0.0.3" }}'
      configmapReload:
        repository: "quay.io/coreos/configmap-reload"
        ### Optional: PROMETHEUS_OPERATOR_CONFIGMAP_RELOAD_IMAGE_TAG; e.g. v0.0.1
        tag: '{{ env "PROMETHEUS_OPERATOR_CONFIGMAP_RELOAD_IMAGE_TAG" | default "v0.0.1" }}'
      kubeletService:
        # If enabled, prometheus-operator will create a service for scraping kubelets
        enable: true
        namespace: "kube-system"
        name: "kubelet"
