helmDefaults:
  args:
    - "--wait"
    - "--recreate-pods"
    - "--timeout=600" 
    - "--force"
    - "--reset-values"

repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:

#######################################################################################
## Grafana                                                                           ##
#######################################################################################

- name: "grafana"
  namespace: "monitoring"
  labels:
    chart: "grafana"
    component: "monitoring"
    namespace: "monitoring"
    vendor: "kubernetes"
    default: "true"
  chart: "stable/grafana"
  version: "1.12.0"
  values:
    - "values/grafana.dashboards.yaml"
    - persistence:
        enabled: true
        size: 10Gi
        accessModes:
          - ReadWriteOnce
      sidecar:
        dashboards:
          enabled: true
        datasources:
          enabled: true
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: 'http://kube-prometheus-prometheus'
              access: proxy
              isDefault: true
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default: {}
      resources:
        limits:
          cpu: "50m"
          memory: "64Mi"
        requests:
          cpu: "10m"
          memory: "64Mi"
