helmDefaults:
  args:
    - "--wait"
    - "--recreate-pods"
    - "--timeout=600" 
    - "--force"
    - "--reset-values"

repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:

#######################################################################################
## Grafana                                                                           ##
#######################################################################################

- name: "grafana"
  namespace: "monitoring"
  labels:
    chart: "grafana"
    component: "monitoring"
    namespace: "monitoring"
    vendor: "kubernetes"
    default: "true"
  chart: "stable/grafana"
  version: "1.12.0"
  values:
    - "values/grafana.dashboards.yaml"
    - datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: 'http://kube-prometheus-prometheus-server'
              access: proxy
              isDefault: true
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          deployment-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/deployment-dashboard.json
          kubernetes-capacity-planning-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/kubernetes-capacity-planning-dashboard.json
          kubernetes-cluster-health-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/kubernetes-cluster-health-dashboard.json
          kubernetes-cluster-status-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/kubernetes-cluster-status-dashboard.json
          kubernetes-control-plane-status-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/kubernetes-control-plane-status-dashboard.json
          kubernetes-resource-requests-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/kubernetes-resource-requests-dashboard.json
          nodes-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/nodes-dashboard.json
          pods-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/pods-dashboard.json
          statefulset-dashboard:
            url: https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/grafana/dashboards/statefulset-dashboard.json
      resources:
        limits:
          cpu: "50m"
          memory: "64Mi"
        requests:
          cpu: "10m"
          memory: "64Mi"
