helmDefaults:
  args:
    - "--wait"
    - "--recreate-pods"
    - "--timeout=600" 
    - "--force"
    - "--reset-values"

repositories:
# Incubator repo of official helm charts
- name: "incubator"
  url: "https://kubernetes-charts-incubator.storage.googleapis.com"

releases:

#######################################################################################
## Fluentd to datadog logs
## Forward logs to Datadog with fluentd                                              ##
#######################################################################################

#
# References:
#   - https://github.com/kubernetes/charts/blob/master/incubator/fluentd/
#   - https://github.com/kubernetes/charts/blob/master/incubator/fluentd/values.yaml
#   - https://github.com/cloudposse/fluentd-datadog-logs
#

- name: "logs"
  namespace: "kube-system"
  labels:
    chart: "fluentd-kubernetes"
    component: "datadog"
    namespace: "kube-system"
    default: "false"
  chart: "cloudposse-incubator/fluentd-kubernetes"
  version: "0.2.0"
  values:
    - image:
        repository: "cloudposse/fluentd-datadog-logs"
        tag: "0.1.1"
        pullPolicy: "Always"
      resources:
        limits:
          cpu: "50m"
          memory: "512Mi"
        requests:
          cpu: "5m"
          memory: "256Mi"
      env:
        open:
          ### Optional: DATADOG_SOURCE;
          DATADOG_SOURCE: '{{ env "DATADOG_SOURCE" | default "k8s-staging" }}'
        secret:
          ### Required: DATADOG_API_KEY;
          DATADOG_API_KEY: '{{ requiredEnv "DATADOG_API_KEY" }}'
      configDir: "/tmp/conf"
