# Build a service with environment variables
version: '1.0'

stages:
  - Prepare
  - Build
  - Push

steps:
  main_clone:
    title: "Clone repository"
    type: git-clone
    stage: Prepare
    description: "Initialize"
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    git: CF-default
    revision: ${{CF_REVISION}}

  build_image:
    title: Build image
    type: build
    stage: Build
    description: Build geodesic
    image_name: ${{CF_REPO_NAME}}
    dockerfile: Dockerfile

  push_image_commit:
    title: Push image with commit sha tag
    type: push
    stage: Push
    candidate: ${{build_image}}
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    registry: dockerhub
    tags:
      - "${{CF_REVISION}}"

  push_image_branch:
    title: Push image with branch tag
    type: push
    stage: Push
    candidate: ${{build_image}}
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    registry: dockerhub
    tags:
      - "${{CF_BRANCH}}"
    when:
      condition:
        all:
          executeForBranch: "'${{CF_BRANCH}}' != ''"
