#image:
#  repository: cloudposse/github-authorized-keys
#  tag: latest
#  pullPolicy: Always
#githubAPIToken: 
#githubOrganization: example
#githubTeam: ssh
# githubTeamID:
# syncUsersGID:
# syncUsersGroups:
# syncUsersShell: "/bin/bash"
# syncUsersInterval: 300
#etcdEnabled: false
#etcdClusterSize: 3
#etcdTTL: "86400"
