#!/bin/bash
function red() {
	echo "$(tput setaf 1)$*$(tput sgr0)"
}

function green() {
	echo "$(tput setaf 2)$*$(tput sgr0)"
}

if [[ $(command -v docker 2> /dev/null) != $(realpath "$0") ]]; then
  red docker stub has detected real docker is installed. Execute
  green "   hash -r"
  red to inform your shell of the new docker binary
  red
  red "executing \"$(command -v docker) $*\""
  exec $(command -v docker) "$@"
fi

red docker command not found.
green To install:
echo "    $(install-docker-command)"
echo
green To inform your shell a new command has been installed
echo "    hash -r"
echo
red Be sure you started Geodesic with the --with-docker option
red or else you will not be able to connect to the Docker daemon socket
echo

