alertmanager:
  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
      external-dns.alpha.kubernetes.io/ttl: "60"
prometheus:
  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
      external-dns.alpha.kubernetes.io/ttl: "60"
