#!/bin/bash

# Function to count active shell sessions launched by wrapper
# Far from perfect:
#   Does not account for shells with detached sessions which cannot be resumed
#   Does not account for shells launched without -l flag in the first position
#   Does not account for alternative shells like rbash or dash
count_shells() {
	pgrep -f "^(/(usr/)?bin/)?(ba)?sh -l" | wc -l
}

kill_shells() {
	pkill -HUP -f "^(/(usr/)?bin/)?(ba)?sh -l"
	for i in {1..4}; do
		[ $(count_shells) -eq 0 ] && return 0
		sleep 1
	done

	pkill -TERM -f "^(/(usr/)?bin/)?(ba)?sh -l"

	for i in {1..3}; do
		[ $(count_shells) -eq 0 ] && return 0
		sleep 1
	done
	pkill -KILL -f "^(/(usr/)?bin/)?(ba)?sh -l"
	return 137
}

trap 'kill_shells; exit $?' TERM HUP INT QUIT EXIT

# Wait up to 4 seconds for the first connection
i=0
while [ $(count_shells) -eq 0 ]; do
	sleep 1
	i=$((i + 1))
	if [ $i -ge 4 ]; then
		echo "No shell sessions detected after 4 seconds, exiting..."
		exit 1
	fi
done

# Monitor shell sessions and exit when none remain
while [ $(count_shells) -gt 0 ]; do
	sleep 1
done

# Clean up and exit
exit 0
